<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Municipality;

class MunicipalitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            ['municipalities' => 'Shadananda', 'district' => '1'],
            ['municipalities' => 'SalpaSilichho', 'district' => '1'],
            ['municipalities' => 'TyamkeMaiyum', 'district' => '1'],
            ['municipalities' => 'Bhojpur', 'district' => '1'],
            ['municipalities' => 'Arun', 'district' => '1'],
            ['municipalities' => 'PauwaDunma', 'district' => '1'],
            ['municipalities' => 'Ramprasad Rai', 'district' => '1'],
            ['municipalities' => 'Hatuwagadhi', 'district' => '1'],
            ['municipalities' => 'Aamchowk', 'district' => '1'],

            ['municipalities' => 'Mahalaxmi', 'district' => '2'],
            ['municipalities' => 'Pakhribas', 'district' => '2'],
            ['municipalities' => 'Chhathar', 'district' => '2'],
            ['municipalities' => 'Dhankuta', 'district' => '2'],
            ['municipalities' => 'KhalsaChhingtangSahidbhumi', 'district' => '2'],
            ['municipalities' => 'Sangurigadhi', 'district' => '2'],
            ['municipalities' => 'Chaubise', 'district' => '2'],

            ['municipalities' => 'Mai Jogmai', 'district' => '3'],
            ['municipalities' => 'Sandakpur', 'district' => '3'],
            ['municipalities' => 'Ilam', 'district' => '3'],
            ['municipalities' => 'Deumai', 'district' => '3'],
            ['municipalities' => 'Fakfothum', 'district' => '3'],
            ['municipalities' => 'Manasebung', 'district' => '3'],
            ['municipalities' => 'Chulachuli', 'district' => '3'],
            ['municipalities' => 'Mai', 'district' => '3'],
            ['municipalities' => 'Suryodaya', 'district' => '3'],
            ['municipalities' => 'Rong', 'district' => '3'],

            ['municipalities' => 'Mechinagar', 'district' => '4'],
            ['municipalities' => 'Buddhashanti', 'district' => '4'],
            ['municipalities' => 'Arjundhara', 'district' => '4'],
            ['municipalities' => 'Kankai', 'district' => '4'],
            ['municipalities' => 'Shivasatakshi', 'district' => '4'],
            ['municipalities' => 'Kamal', 'district' => '4'],
            ['municipalities' => 'Damak', 'district' => '4'],
            ['municipalities' => 'Gauradaha', 'district' => '4'],
            ['municipalities' => 'Gauriganj', 'district' => '4'],
            ['municipalities' => 'Jhapa', 'district' => '4'],
            ['municipalities' => 'Barhadashi', 'district' => '4'],
            ['municipalities' => 'Birtamod', 'district' => '4'],
            ['municipalities' => 'Haldibari', 'district' => '4'],
            ['municipalities' => 'Bhadrapur', 'district' => '4'],
            ['municipalities' => 'Kanchanakawal', 'district' => '4'],



            ['municipalities' => 'Kepilasgadhi', 'district' => '5'],
            ['municipalities' => 'Aiselukharka', 'district' => '5'],
            ['municipalities' => 'Lamidanada', 'district' => '5'],
            ['municipalities' => 'HalesiTuwachung', 'district' => '5'],
            ['municipalities' => 'RupakotMajhuwagadi', 'district' => '5'],
            ['municipalities' => 'Sakela', 'district' => '5'],
            ['municipalities' => 'Diprung', 'district' => '5'],
            ['municipalities' => 'Khotehang', 'district' => '5'],
            ['municipalities' => 'JanteDhunga', 'district' => '5'],
            ['municipalities' => 'BarahaPokhari', 'district' => '5'],

            ['municipalities' => 'Miklajung', 'district' => '6'],
            ['municipalities' => 'Letang', 'district' => '6'],
            ['municipalities' => 'Kerabari', 'district' => '6'],
            ['municipalities' => 'Sundarharaicha', 'district' => '6'],
            ['municipalities' => 'Belbari', 'district' => '6'],
            ['municipalities' => 'PathariShanishchare', 'district' => '6'],
            ['municipalities' => 'Urlabari', 'district' => '6'],
            ['municipalities' => 'Ratuwamai', 'district' => '6'],
            ['municipalities' => 'Sunwarshi', 'district' => '6'],
            ['municipalities' => 'Rangeli', 'district' => '6'],
            ['municipalities' => 'Gramthan', 'district' => '6'],
            ['municipalities' => 'Budhiganga', 'district' => '6'],
            ['municipalities' => 'BirtnagarMetropolitianCity', 'district' => '6'],
            ['municipalities' => 'Katahari', 'district' => '6'],
            ['municipalities' => 'Dhanapalthan', 'district' => '6'],
            ['municipalities' => 'Jahada', 'district' => '6'],

            ['municipalities' => 'ChishankhuGadhi', 'district' => '7'],
            ['municipalities' => 'Siddhicharan', 'district' => '7'],
            ['municipalities' => 'Molung', 'district' => '7'],
            ['municipalities' => 'KhijiDemda', 'district' => '7'],
            ['municipalities' => 'Likhu', 'district' => '7'],
            ['municipalities' => 'Champadevi', 'district' => '7'],
            ['municipalities' => 'Sunkhosi', 'district' => '7'],
            ['municipalities' => 'Manebhanjyang', 'district' => '7'],
            ['municipalities' => 'Yangbarak', 'district' => '8'],
            ['municipalities' => 'Hilihan', 'district' => '8'],
            ['municipalities' => 'Falelung', 'district' => '8'],
            ['municipalities' => 'Kummayak', 'district' => '8'],
            ['municipalities' => 'Tumbewa', 'district' => '8'],
            ['municipalities' => 'Miklajung', 'district' => '8'],

            ['municipalities' => 'Phaktanlung', 'district' => '9'],
            ['municipalities' => 'Mikwakhola', 'district' => '9'],
            ['municipalities' => 'Meringden', 'district' => '9'],
            ['municipalities' => 'Maikhola', 'district' => '9'],
            ['municipalities' => 'AathariTribeni', 'district' => '9'],
            ['municipalities' => 'Phungling', 'district' => '9'],
            ['municipalities' => 'Yangwarak', 'district' => '9'],
            ['municipalities' => 'Sirijanga', 'district' => '9'],
            ['municipalities' => 'Sidingba', 'district' => '9'],


            ['municipalities' => 'Aatharai', 'district' => '10'],
            ['municipalities' => 'Phedap', 'district' => '10'],
            ['municipalities' => 'Menchhayem', 'district' => '10'],
            ['municipalities' => 'Myanglung', 'district' => '10'],
            ['municipalities' => 'laligurans', 'district' => '10'],
            ['municipalities' => 'Chhathar', 'district' => '10'],

            ['municipalities' => 'Bhotkhola', 'district' => '11'],
            ['municipalities' => 'Makalu', 'district' => '11'],
            ['municipalities' => 'Silichong', 'district' => '11'],
            ['municipalities' => 'Chichila', 'district' => '11'],
            ['municipalities' => 'Sabhapokhari', 'district' => '11'],
            ['municipalities' => 'Khandabari', 'district' => '11'],
            ['municipalities' => 'Panchakhapan', 'district' => '11'],
            ['municipalities' => 'Chainapur', 'district' => '11'],
            ['municipalities' => 'Madi', 'district' => '11'],
            ['municipalities' => 'Dharmadevi', 'district' => '11'],

            ['municipalities' => 'KhumbuPasanglhamu', 'district' => '12'],
            ['municipalities' => 'Mahakulung', 'district' => '12'],
            ['municipalities' => 'Sotang', 'district' => '12'],
            ['municipalities' => 'DHudhakhoshi', 'district' => '12'],
            ['municipalities' => 'DhudhaKoushika', 'district' => '12'],
            ['municipalities' => 'Nechasalyan', 'district' => '12'],
            ['municipalities' => 'SoluDhudhakunda', 'district' => '12'],
            ['municipalities' => 'Likhu pike', 'district' => '12'],

            ['municipalities' => 'Dharan sub-metropolitian city', 'district' => '13'],
            ['municipalities' => 'Baraha', 'district' => '13'],
            ['municipalities' => 'Koshi', 'district' => '13'],
            ['municipalities' => 'Bhokraha', 'district' => '13'],
            ['municipalities' => 'Ramdhuni', 'district' => '13'],
            ['municipalities' => 'Itahari sub-metropolitian city',     'district' => '13'],
            ['municipalities' => 'Duhabi', 'district' => '13'],
            ['municipalities' => 'Gadhi', 'district' => '13'],
            ['municipalities' => 'Inaruwa', 'district' => '13'],
            ['municipalities' => 'Harinagara', 'district' => '13'],
            ['municipalities' => 'Dewangunj', 'district' => '13'],
            ['municipalities' => 'Barju', 'district' => '13'],

            ['municipalities' => 'Belaka', 'district' => '14'],
            ['municipalities' => 'Chaudandigadhi', 'district' => '14'],
            ['municipalities' => 'Triyuga', 'district' => '14'],
            ['municipalities' => 'Rautamai', 'district' => '14'],
            ['municipalities' => 'Sunkoshi', 'district' => '14'],
            ['municipalities' => 'Tapli', 'district' => '14'],
            ['municipalities' => 'Katari', 'district' => '14'],
            ['municipalities' => 'Udayapurgadhi', 'district' => '14'],


            ['municipalities' => 'Nijagadn', 'district' => '15'],
            ['municipalities' => 'Kolhabi', 'district' => '15'],
            ['municipalities' => 'Jitpur', 'district' => '15'],
            ['municipalities' => 'Parawanipur', 'district' => '15'],
            ['municipalities' => 'Prasauni', 'district' => '15'],
            ['municipalities' => 'Bishrampur', 'district' => '15'],
            ['municipalities' => 'Pheta', 'district' => '15'],
            ['municipalities' => 'Kaliya', 'district' => '15'],
            ['municipalities' => 'Kariyamai', 'district' => '15'],
            ['municipalities' => 'Baragadhi', 'district' => '15'],
            ['municipalities' => 'Simroungadh', 'district' => '15'],
            ['municipalities' => 'pacharauta', 'district' => '15'],
            ['municipalities' => 'Managadhimai', 'district' => '15'],
            ['municipalities' => 'Devtal', 'district' => '15'],
            ['municipalities' => 'Subarna', 'district' => '15'],
            ['municipalities' => 'AadarshaKotwal', 'district' => '15'],

            ['municipalities' => 'GaneshmanCharnath', 'district' => '16'],
            ['municipalities' => 'Dhanushwornath', 'district' => '16'],
            ['municipalities' => 'Mithila', 'district' => '16'],
            ['municipalities' => 'Bateshwar', 'district' => '16'],
            ['municipalities' => 'Chhireshwornath', 'district' => '16'],
            ['municipalities' => 'Laxminiya', 'district' => '16'],
            ['municipalities' => 'Mithila Bhari', 'district' => '16'],
            ['municipalities' => 'Hansapur', 'district' => '16'],
            ['municipalities' => 'Sabaila', 'district' => '16'],
            ['municipalities' => 'Shahidnagar', 'district' => '16'],
            ['municipalities' => 'Kamala', 'district' => '16'],
            ['municipalities' => 'JanakNandini', 'district' => '16'],
            ['municipalities' => 'Bideha', 'district' => '16'],
            ['municipalities' => 'Aurahi', 'district' => '16'],
            ['municipalities' => 'Janakpur ', 'district' => '16'],
            ['municipalities' => 'Dhanauji', 'district' => '16'],
            ['municipalities' => 'Nagarain', 'district' => '16'],
            ['municipalities' => 'Mukhiyapati Musaharmiya', 'district' => '16'],

            ['municipalities' => 'Aurahi', 'district' => '17'],
            ['municipalities' => 'Bardibas', 'district' => '17'],
            ['municipalities' => 'Balawa', 'district' => '17'],
            ['municipalities' => 'Ekadara', 'district' => '17'],
            ['municipalities' => 'Gaushala', 'district' => '17'],
            ['municipalities' => 'Sonama', 'district' => '17'],
            ['municipalities' => 'Bhangaha', 'district' => '17'],
            ['municipalities' => 'loharpati', 'district' => '17'],
            ['municipalities' => 'Ram Gopalpu', 'district' => '17'],
            ['municipalities' => 'Samsi', 'district' => '17'],
            ['municipalities' => 'ManaraShisawa', 'district' => '17'],
            ['municipalities' => 'Mahottari', 'district' => '17'],
            ['municipalities' => 'Pipra', 'district' => '17'],
            ['municipalities' => 'Matihani', 'district' => '17'],
            ['municipalities' => 'Jalesshwor', 'district' => '17'],

            ['municipalities' => 'Bindabasini', 'district' => '18'],
            ['municipalities' => 'Chhipharmai', 'district' => '18'],
            ['municipalities' => 'Dhobini', 'district' => '18'],
            ['municipalities' => 'Thori', 'district' => '18'],
            ['municipalities' => 'Jirabhaani', 'district' => '18'],
            ['municipalities' => 'Jagarnathpur', 'district' => '18'],
            ['municipalities' => 'PaterwaSugauli', 'district' => '18'],
            ['municipalities' => 'SakhuwaPrasuni', 'district' => '18'],
            ['municipalities' => 'Parsagadhi', 'district' => '18'],
            ['municipalities' => 'Birgunj', 'district' => '18'],
            ['municipalities' => 'Bahudarmai', 'district' => '18'],
            ['municipalities' => 'Dhobini', 'district' => '18'],
            ['municipalities' => 'PakahaMainpur', 'district' => '18'],

            ['municipalities' => 'Gujara', 'district' => '19'],
            ['municipalities' => 'PhatuwaBijayapur', 'district' => '19'],
            ['municipalities' => 'Katahariya', 'district' => '19'],
            ['municipalities' => 'Brindaban', 'district' => '19'],
            ['municipalities' => 'Gadhimai', 'district' => '19'],
            ['municipalities' => 'Madhav Narayan', 'district' => '19'],
            ['municipalities' => 'Garuda', 'district' => '19'],
            ['municipalities' => 'DewahiGonahi', 'district' => '19'],
            ['municipalities' => 'Rajdevi', 'district' => '19'],
            ['municipalities' => 'Gaur', 'district' => '19'],
            ['municipalities' => 'Ishanath', 'district' => '19'],
            ['municipalities' => 'Chandrapur', 'district' => '19'],

            ['municipalities' => 'Saptakoshi', 'district' => '20'],
            ['municipalities' => 'Kanchanrup', 'district' => '20'],
            ['municipalities' => 'Agnisair Krishna Sabaran', 'district' => '20'],
            ['municipalities' => 'Rupani', 'district' => '20'],
            ['municipalities' => 'Shambhunath', 'district' => '20'],
            ['municipalities' => 'Khadak', 'district' => '20'],
            ['municipalities' => 'Surunga', 'district' => '20'],
            ['municipalities' => 'BalanBihul', 'district' => '20'],
            ['municipalities' => 'Bode Barsain', 'district' => '20'],
            ['municipalities' => 'Dakneshwori', 'district' => '20'],
            ['municipalities' => 'BelhiChapena', 'district' => '20'],
            ['municipalities' => 'Bishnupur', 'district' => '20'],
            ['municipalities' => 'Rajbiraj', 'district' => '20'],
            ['municipalities' => 'Mahadewa', 'district' => '20'],
            ['municipalities' => 'Tirahut', 'district' => '20'],
            ['municipalities' => 'HanumannagarKankalini', 'district' => '20'],
            ['municipalities' => 'TilathiKailadi', 'district' => '20'],
            ['municipalities' => 'Chhinnamaste', 'district' => '20'],

            ['municipalities' => 'Parsa', 'district' => '21'],
            ['municipalities' => 'Lalbndi', 'district' => '21'],
            ['municipalities' => 'Hariwan', 'district' => '21'],
            ['municipalities' => 'Bagmati', 'district' => '21'],
            ['municipalities' => 'Barahathawa', 'district' => '21'],
            ['municipalities' => 'Haripur', 'district' => '21'],
            ['municipalities' => 'Ishworpur', 'district' => '21'],
            ['municipalities' => 'Haripurwa', 'district' => '21'],
            ['municipalities' => 'Brahmapuri', 'district' => '21'],
            ['municipalities' => 'Chandranagar', 'district' => '21'],
            ['municipalities' => 'Kabilashi', 'district' => '21'],
            ['municipalities' => 'Chakraghatta', 'district' => '21'],
            ['municipalities' => 'Basbariya', 'district' => '21'],
            ['municipalities' => 'Dhanakual', 'district' => '21'],
            ['municipalities' => 'Ramnagar', 'district' => '21'],
            ['municipalities' => 'Balara', 'district' => '21'],
            ['municipalities' => 'Godaita', 'district' => '21'],
            ['municipalities' => 'Bishnu', 'district' => '21'],
            ['municipalities' => 'Kaudena', 'district' => '21'],
            ['municipalities' => 'Malangawa', 'district' => '21'],

            ['municipalities' => 'Lahan', 'district' => '22'],
            ['municipalities' => 'Dhangadhimai', 'district' => '22'],
            ['municipalities' => 'Golbazar', 'district' => '22'],
            ['municipalities' => 'Mirchariya', 'district' => '22'],
            ['municipalities' => 'Karjanha', 'district' => '22'],
            ['municipalities' => 'Naraha', 'district' => '22'],
            ['municipalities' => 'Bishnupur', 'district' => '22'],
            ['municipalities' => 'Arnama', 'district' => '22'],
            ['municipalities' => 'Sukhipur', 'district' => '22'],
            ['municipalities' => 'LaxmipurPatari', 'district' => '22'],
            ['municipalities' => 'SakhuwaNankarkatti', 'district' => '22'],
            ['municipalities' => 'Bhagawanpur', 'district' => '22'],
            ['municipalities' => 'Nawarajpur', 'district' => '22'],
            ['municipalities' => 'Bariyarpatti', 'district' => '22'],
            ['municipalities' => 'Aurahi', 'district' => '22'],
            ['municipalities' => 'iraha', 'district' => '22'],

            ['municipalities' => 'Changunarayan', 'district' => '23'],
            ['municipalities' => 'Bhaktapur', 'district' => '23'],
            ['municipalities' => 'Madhyapurthimi', 'district' => '23'],
            ['municipalities' => 'Suryabinayak', 'district' => '23'],

            ['municipalities' => 'Rapti', 'district' => '24'],
            ['municipalities' => 'Kalika', 'district' => '24'],
            ['municipalities' => 'Ichchhakamana', 'district' => '24'],
            ['municipalities' => 'Bharatpurmetropolitian city', 'district' => '24'],
            ['municipalities' => 'Ratnanagar', 'district' => '24'],
            ['municipalities' => 'Khairahani', 'district' => '24'],
            ['municipalities' => 'Madi', 'district' => '24'],

            ['municipalities' => 'Rubi Valley', 'district' => '25'],
            ['municipalities' => 'Khaniyabas', 'district' => '25'],
            ['municipalities' => 'Ganga Jamuna', 'district' => '25'],
            ['municipalities' => 'Tripurasundari', 'district' => '25'],
            ['municipalities' => 'Netrawati', 'district' => '25'],
            ['municipalities' => 'Nikhantha', 'district' => '25'],
            ['municipalities' => 'Jwalamukhi', 'district' => '25'],
            ['municipalities' => 'Siddhalek', 'district' => '25'],
            ['municipalities' => 'BenighatRorang', 'district' => '25'],
            ['municipalities' => 'Gajuri', 'district' => '25'],
            ['municipalities' => 'Galchi', 'district' => '25'],
            ['municipalities' => 'Thakre', 'district' => '25'],
            ['municipalities' => 'Dhunibenshi', 'district' => '25'],

            ['municipalities' => 'Gaurishankar', 'district' => '26'],
            ['municipalities' => 'Bigu', 'district' => '26'],
            ['municipalities' => 'Kalinchowk', 'district' => '26'],
            ['municipalities' => 'Baitedhar', 'district' => '26'],
            ['municipalities' => 'Jiri', 'district' => '26'],
            ['municipalities' => 'Tamakoshi', 'district' => '26'],
            ['municipalities' => 'Melung', 'district' => '26'],
            ['municipalities' => 'Shailung', 'district' => '26'],
            ['municipalities' => 'Bhimeshwor', 'district' => '26'],


            ['municipalities' => 'Shankharapur', 'district' => '27'],
            ['municipalities' => 'KageshworiManahara', 'district' => '27'],
            ['municipalities' => 'Gokarneshwor', 'district' => '27'],
            ['municipalities' => 'Budhanilkhantha', 'district' => '27'],
            ['municipalities' => 'Tokha', 'district' => '27'],
            ['municipalities' => 'Tarakeshwor', 'district' => '27'],
            ['municipalities' => 'Nagarjun', 'district' => '27'],
            ['municipalities' => 'Kathmandu metropolitiancity', 'district' => '27'],
            ['municipalities' => 'Kirtipur', 'district' => '27'],
            ['municipalities' => 'Chandragiri', 'district' => '27'],
            ['municipalities' => 'Dakshinkali', 'district' => '27'],


            ['municipalities' => 'ChauriDeurali', 'district' => '28'],
            ['municipalities' => 'Bhumlu', 'district' => '28'],
            ['municipalities' => 'Mandan Deupur', 'district' => '28'],
            ['municipalities' => 'Banepa', 'district' => '28'],
            ['municipalities' => 'Dhulikhel', 'district' => '28'],
            ['municipalities' => 'Panchkhal', 'district' => '28'],
            ['municipalities' => 'Temal', 'district' => '28'],
            ['municipalities' => 'Namobuddha', 'district' => '28'],
            ['municipalities' => 'Panauti', 'district' => '28'],
            ['municipalities' => 'Bethanchowk', 'district' => '28'],
            ['municipalities' => 'Roshi', 'district' => '28'],
            ['municipalities' => 'Mahabharat', 'district' => '28'],
            ['municipalities' => 'Khanikhola', 'district' => '28'],


            ['municipalities' => 'Mahalaxmi', 'district' => '29'],
            ['municipalities' => 'Lalitpurmertopolitiancity', 'district' => '29'],
            ['municipalities' => 'Godawari', 'district' => '29'],
            ['municipalities' => 'Konijyosom', 'district' => '29'],
            ['municipalities' => 'Mahankhal', 'district' => '29'],
            ['municipalities' => 'Bagmait', 'district' => '29'],

            ['municipalities' => 'Indrasarowar', 'district' => '30'],
            ['municipalities' => 'Thaha', 'district' => '30'],
            ['municipalities' => 'Kailash', 'district' => '30'],
            ['municipalities' => 'Raksirang', 'district' => '30'],
            ['municipalities' => 'Manahari', 'district' => '30'],
            ['municipalities' => 'Hetauda sub-                metropolitiancity', 'district' => '30'],
            ['municipalities' => 'Bhimphedi', 'district' => '30'],
            ['municipalities' => 'Makawanpurgadhi', 'district' => '30'],
            ['municipalities' => 'Bakaiya', 'district' => '30'],
            ['municipalities' => 'Bagmati', 'district' => '30'],

            ['municipalities' => 'Dupcheshwor', 'district' => '31'],
            ['municipalities' => 'Tadi', 'district' => '31'],
            ['municipalities' => 'Suryagadhi', 'district' => '31'],
            ['municipalities' => 'Bidur', 'district' => '31'],
            ['municipalities' => 'Kispang', 'district' => '31'],
            ['municipalities' => 'Meghang', 'district' => '31'],
            ['municipalities' => 'Tarakeshwor', 'district' => '31'],
            ['municipalities' => 'Belkotgadhi', 'district' => '31'],
            ['municipalities' => 'Likhu', 'district' => '31'],
            ['municipalities' => 'Panchakanya', 'district' => '31'],
            ['municipalities' => 'Shivapuri', 'district' => '31'],
            ['municipalities' => 'kakani', 'district' => '31'],

            ['municipalities' => 'Umakunda', 'district' => '32'],
            ['municipalities' => 'Gokulganga', 'district' => '32'],
            ['municipalities' => 'Likhu', 'district' => '32'],
            ['municipalities' => 'Ramechhap', 'district' => '32'],
            ['municipalities' => 'Manthali', 'district' => '32'],
            ['municipalities' => 'Khandadevi', 'district' => '32'],
            ['municipalities' => 'Doramba', 'district' => '32'],
            ['municipalities' => 'Sunapati', 'district' => '32'],

            ['municipalities' => 'Gosaikunda', 'district' => '33'],
            ['municipalities' => 'Parbatikunda', 'district' => '33'],
            ['municipalities' => 'Uttargaya', 'district' => '33'],
            ['municipalities' => 'Kalika', 'district' => '33'],
            ['municipalities' => 'Naukunda', 'district' => '33'],

            ['municipalities' => 'Dudhouli', 'district' => '34'],
            ['municipalities' => 'Phikkal', 'district' => '34'],
            ['municipalities' => 'Tinpatan', 'district' => '34'],
            ['municipalities' => 'Golanjor', 'district' => '34'],
            ['municipalities' => 'Kamalamai', 'district' => '34'],
            ['municipalities' => 'Sunhoshi', 'district' => '34'],
            ['municipalities' => 'Ghyanglekha', 'district' => '34'],
            ['municipalities' => 'Marin', 'district' => '34'],
            ['municipalities' => 'Hariharpurgadhi', 'district' => '34'],

            ['municipalities' => 'Bhotekosi', 'district' => '35'],
            ['municipalities' => 'Jungal', 'district' => '35'],
            ['municipalities' => 'Panchpokhari', 'district' => '35'],
            ['municipalities' => 'Helambu', 'district' => '35'],
            ['municipalities' => 'Melanchi', 'district' => '35'],
            ['municipalities' => 'Indrawoti', 'district' => '35'],
            ['municipalities' => 'Choutarasangachowkgadhi', 'district' => '35'],
            ['municipalities' => 'Balephi', 'district' => '35'],
            ['municipalities' => 'Bahrabise', 'district' => '35'],
            ['municipalities' => 'Tripurasundari', 'district' => '35'],
            ['municipalities' => 'Lisankhupakhar', 'district' => '35'],
            ['municipalities' => 'Sunkoshi', 'district' => '35'],

            ['municipalities' => 'Baglung', 'district' => '36'],
            ['municipalities' => 'Badigad', 'district' => '36'],
            ['municipalities' => 'Kathekhola', 'district' => '36'],
            ['municipalities' => 'Tamankhola', 'district' => '36'],
            ['municipalities' => 'Dhorpatan', 'district' => '36'],
            ['municipalities' => 'Nisikhola', 'district' => '36'],
            ['municipalities' => 'Galkot', 'district' => '36'],
            ['municipalities' => 'Jaimuni', 'district' => '36'],

            ['municipalities' => 'Bareng', 'district' => '37'],
            ['municipalities' => 'Chumanubri', 'district' => '23'],
            ['municipalities' => 'Ajirkot', 'district' => '23'],
            ['municipalities' => 'Sulikot', 'district' => '23'],
            ['municipalities' => 'Dharche', 'district' => '23'],
            ['municipalities' => 'Aarughat', 'district' => '23'],
            ['municipalities' => 'Bhimsen', 'district' => '37'],
            ['municipalities' => 'Siranchowk', 'district' => '37'],
            ['municipalities' => 'Palungtar', 'district' => '37'],
            ['municipalities' => 'Gorkha', 'district' => '37'],
            ['municipalities' => 'Shahid Lakhan', 'district' => '37'],
            ['municipalities' => 'Gandaki', 'district' => '37'],

            ['municipalities' => 'Madi', 'district' => '38'],
            ['municipalities' => 'Annapurna', 'district' => '38'],
            ['municipalities' => 'Pokhara Lekhnath', 'district' => '38'],
            ['municipalities' => 'Rupa', 'district' => '38'],

            ['municipalities' => 'Dordi', 'district' => '39'],
            ['municipalities' => 'Marshyangdi', 'district' => '39'],
            ['municipalities' => 'Kwhola Sothar', 'district' => '39'],
            ['municipalities' => 'Madhya', 'district' => '39'],
            ['municipalities' => 'Bensi  Shahar', 'district' => '39'],
            ['municipalities' => 'Sundarbazar', 'district' => '39'],
            ['municipalities' => 'Rainas', 'district' => '39'],
            ['municipalities' => 'Dudhapokhari', 'district' => '39'],

            ['municipalities' => 'Naraphu', 'district' => '40'],
            ['municipalities' => 'Neshang', 'district' => '40'],
            ['municipalities' => 'Chame', 'district' => '40'],
            ['municipalities' => 'Nashong', 'district' => '40'],

            ['municipalities' => 'Dalome', 'district' => '41'],
            ['municipalities' => 'Gharpajhong', 'district' => '41'],
            ['municipalities' => 'Bahragaun Muktishetra', 'district' => '41'],
            ['municipalities' => 'Lomanthang', 'district' => '41'],
            ['municipalities' => 'Thasang', 'district' => '41'],

            ['municipalities' => 'Annapurna', 'district' => '42'],
            ['municipalities' => 'Raghuganga', 'district' => '42'],
            ['municipalities' => 'Dhawalagiri', 'district' => '42'],
            ['municipalities' => 'Malika', 'district' => '42'],
            ['municipalities' => 'Mangala', 'district' => '42'],
            ['municipalities' => 'Beni', 'district' => '42'],

            ['municipalities' => 'Binayi  Tribeni', 'district' => '43'],
            ['municipalities' => 'Bulingtar', 'district' => '43'],
            ['municipalities' => 'Bungdikali', 'district' => '43'],
            ['municipalities' => 'Devchuli', 'district' => '43'],
            ['municipalities' => 'Gaidakot', 'district' => '43'],
            ['municipalities' => 'Hupsekot', 'district' => '43'],
            ['municipalities' => 'Kawasoti', 'district' => '43'],
            ['municipalities' => 'Madhya Bindu', 'district' => '43'],

            ['municipalities' => 'Modi', 'district' => '44'],
            ['municipalities' => 'Jaljala', 'district' => '44'],
            ['municipalities' => 'Kushma', 'district' => '44'],
            ['municipalities' => 'Phalebas', 'district' => '44'],
            ['municipalities' => 'Mahashila', 'district' => '44'],
            ['municipalities' => 'Bihadi', 'district' => '44'],
            ['municipalities' => 'Paiyu', 'district' => '44'],

            ['municipalities' => 'Putalibazar', 'district' => '45'],
            ['municipalities' => 'Phedikhola', 'district' => '45'],
            ['municipalities' => 'Aandhikhola', 'district' => '45'],
            ['municipalities' => 'Bhirkot', 'district' => '45'],
            ['municipalities' => 'Biruwa', 'district' => '45'],
            ['municipalities' => 'Harinas', 'district' => '45'],
            ['municipalities' => 'Chapakot', 'district' => '45'],
            ['municipalities' => 'Waling', 'district' => '45'],
            ['municipalities' => 'Galyang', 'district' => '45'],
            ['municipalities' => 'Kaligandaki', 'district' => '45'],

            ['municipalities' => 'Bhanu', 'district' => '46'],
            ['municipalities' => 'Byas', 'district' => '46'],
            ['municipalities' => 'Myagde', 'district' => '46'],
            ['municipalities' => 'Shuklagandaki', 'district' => '46'],
            ['municipalities' => 'Bhimad', 'district' => '46'],
            ['municipalities' => 'Ghiring', 'district' => '46'],
            ['municipalities' => 'Rhishing', 'district' => '46'],
            ['municipalities' => 'Devghat', 'district' => '46'],
            ['municipalities' => 'Bindipur', 'district' => '46'],
            ['municipalities' => 'Aanbu Khaireni', 'district' => '46'],


            ['municipalities' => 'Chhatradev', 'district' => '47'],
            ['municipalities' => 'Malarani', 'district' => '47'],
            ['municipalities' => 'Bhumikastan', 'district' => '47'],
            ['municipalities' => 'Sandhikharka', 'district' => '47'],
            ['municipalities' => 'Panini', 'district' => '47'],
            ['municipalities' => 'Shitagana', 'district' => '47'],

            ['municipalities' => 'Rapti Sonari', 'district' => '48'],
            ['municipalities' => 'Kohalpur', 'district' => '48'],
            ['municipalities' => 'Baijanath', 'district' => '48'],
            ['municipalities' => 'Khajura', 'district' => '48'],
            ['nuame' => 'Janaki', 'district' => '48'],
            ['municipalities' => 'Nepalganj', 'district' => '48'],
            ['municipalities' => 'Duduwa', 'district' => '48'],
            ['municipalities' => 'Narainapur', 'district' => '48'],

            ['municipalities' => 'Bansgadhi', 'district' => '49'],
            ['municipalities' => 'Barbardiya', 'district' => '49'],
            ['municipalities' => 'Thakurbaba', 'district' => '49'],
            ['municipalities' => 'Geruwa', 'district' => '49'],
            ['municipalities' => 'Rajapur', 'district' => '49'],
            ['municipalities' => 'Madhuwan', 'district' => '49'],
            ['municipalities' => 'Gulariya', 'district' => '49'],
            ['municipalities' => 'Badhaiyatal', 'district' => '49'],

            ['municipalities' => 'Bangalachuli', 'district' => '50'],
            ['municipalities' => 'Ghorahi', 'district' => '50'],
            ['municipalities' => 'Tulsipur', 'district' => '50'],
            ['municipalities' => 'Shantinagar', 'district' => '50'],
            ['municipalities' => 'Babai', 'district' => '50'],
            ['municipalities' => 'Dangisharan', 'district' => '50'],
            ['municipalities' => 'Lamahi', 'district' => '50'],
            ['municipalities' => 'Rapti', 'district' => '50'],
            ['municipalities' => 'Gadhawa', 'district' => '50'],
            ['municipalities' => 'Rajpur', 'district' => '50'],


            ['municipalities' => 'kali Gandaki', 'district' => '51'],
            ['municipalities' => 'Satyawoti', 'district' => '51'],
            ['municipalities' => 'Chandrakot', 'district' => '51'],
            ['municipalities' => 'Musikot', 'district' => '51'],
            ['municipalities' => 'Isam', 'district' => '51'],
            ['municipalities' => 'Malika', 'district' => '51'],
            ['municipalities' => 'Madane', 'district' => '51'],
            ['municipalities' => 'Dhurkot', 'district' => '51'],
            ['municipalities' => 'Resunga', 'district' => '51'],
            ['municipalities' => 'Gulmi Durbar', 'district' => '51'],
            ['municipalities' => 'Chhatrakot', 'district' => '51'],
            ['municipalities' => 'Ruru', 'district' => '51'],

            ['municipalities' => 'Banganga', 'district' => '52'],
            ['municipalities' => 'Buddhahbumi', 'district' => '52'],
            ['municipalities' => 'Shivraj', 'district' => '52'],
            ['municipalities' => 'Bijayraj', 'district' => '52'],
            ['municipalities' => 'Krishnanagar', 'district' => '52'],
            ['municipalities' => 'Maharajganj', 'district' => '52'],
            ['municipalities' => 'Kapilbastu', 'district' => '52'],
            ['municipalities' => 'Yasodhara', 'district' => '52'],
            ['municipalities' => 'Mayadevi', 'district' => '52'],
            ['municipalities' => 'Shuddhodhan', 'district' => '52'],

            ['municipalities' => 'Bardaghat', 'district' => '53'],
            ['municipalities' => 'Sunawal', 'district' => '53'],
            ['municipalities' => 'Ramgram', 'district' => '53'],
            ['municipalities' => 'Palhinandan', 'district' => '53'],
            ['municipalities' => 'Sarawal', 'district' => '53'],
            ['municipalities' => 'Susta', 'district' => '53'],

            ['municipalities' => 'Rampur', 'district' => '54'],
            ['municipalities' => 'Purbakhola', 'district' => '54'],
            ['municipalities' => 'Rambha', 'district' => '54'],
            ['municipalities' => 'Baganaskali', 'district' => '54'],
            ['municipalities' => 'Tansen', 'district' => '54'],
            ['municipalities' => 'Ribdikot', 'district' => '54'],
            ['municipalities' => 'Rainadevi Chhahara', 'district' => '54'],
            ['municipalities' => 'Tinau', 'district' => '54'],
            ['municipalities' => 'Mathagadhi', 'district' => '54'],
            ['municipalities' => 'Nasdi', 'district' => '54'],

            ['municipalities' => 'Gaumukhi', 'district' => '55'],
            ['municipalities' => 'Naubahini', 'district' => '55'],
            ['municipalities' => 'Jhimaruk', 'district' => '55'],
            ['municipalities' => 'Pyuthan', 'district' => '55'],
            ['municipalities' => 'Sworgadwari', 'district' => '55'],
            ['municipalities' => 'Mandavi', 'district' => '55'],
            ['municipalities' => 'Mallarani', 'district' => '55'],
            ['municipalities' => 'Aairawati', 'district' => '55'],
            ['municipalities' => 'Sarumarani', 'district' => '55'],

            ['municipalities' => 'Sunchhahari', 'district' => '56'],
            ['municipalities' => 'Thawang', 'district' => '56'],
            ['municipalities' => 'Duilkholi', 'district' => '56'],
            ['municipalities' => 'Sukidaha', 'district' => '56'],
            ['municipalities' => 'Madi', 'district' => '56'],
            ['municipalities' => 'Tribeni', 'district' => '56'],
            ['municipalities' => 'Rolpa', 'district' => '56'],
            ['municipalities' => 'Runtigadhi', 'district' => '56'],
            ['municipalities' => 'Subarnabati', 'district' => '56'],
            ['municipalities' => 'Lungri', 'district' => '56'],

            ['municipalities' => 'Putha Uttanganga', 'district' => '57'],
            ['municipalities' => 'Sisne', 'district' => '57'],
            ['municipalities' => 'Bhoome', 'district' => '57'],

            ['municipalities' => 'Devdaha', 'district' => '58'],
            ['municipalities' => 'Butwal ', 'district' => '58'],
            ['municipalities' => 'Sainamaina', 'district' => '58'],
            ['municipalities' => 'Kanchan', 'district' => '58'],
            ['municipalities' => 'Gaidahawa', 'district' => '58'],
            ['municipalities' => 'Suddhodhan', 'district' => '58'],
            ['municipalities' => 'Siyari', 'district' => '58'],
            ['municipalities' => 'Tilottama', 'district' => '58'],
            ['municipalities' => 'Om Satiya', 'district' => '58'],
            ['municipalities' => 'Rohini', 'district' => '58'],
            ['municipalities' => 'Siddarthanagar', 'district' => '58'],
            ['municipalities' => 'Mayadevi', 'district' => '58'],
            ['municipalities' => 'Lumbini Sanskritik', 'district' => '58'],
            ['municipalities' => 'Kotahimai', 'district' => '58'],
            ['municipalities' => 'Sammarimai', 'district' => '58'],
            ['municipalities' => 'Marchawari', 'district' => '58'],


            ['municipalities' => 'Naumule', 'district' => '59'],
            ['municipalities' => 'Mahabu', 'district' => '59'],
            ['municipalities' => 'Bhairabi', 'district' => '59'],
            ['municipalities' => 'Thantikandh', 'district' => '59'],
            ['municipalities' => 'Aathbis', 'district' => '59'],
            ['municipalities' => 'Chamunda Bindrasaini', 'district' => '59'],
            ['municipalities' => 'Dullu', 'district' => '59'],
            ['municipalities' => 'Narayan', 'district' => '59'],
            ['municipalities' => 'Bhagawatimai', 'district' => '59'],
            ['municipalities' => 'Dungeshwor', 'district' => '59'],
            ['municipalities' => 'Gurans', 'district' => '59'],



            ['municipalities' => 'Dolpo Buddha', 'district' => '60'],
            ['municipalities' => 'Shey phoksundo', 'district' => '60'],
            ['municipalities' => 'Jagadulla', 'district' => '60'],
            ['municipalities' => 'Mudkechula', 'district' => '60'],
            ['municipalities' => 'Tripurasundari', 'district' => '60'],
            ['municipalities' => 'Thulibheri', 'district' => '60'],
            ['municipalities' => 'Kaike', 'district' => '60'],
            ['municipalities' => 'Chharka', 'district' => '60'],



            ['municipalities' => 'Chankheli', 'district' => '61'],
            ['municipalities' => 'Kharpunath', 'district' => '61'],
            ['municipalities' => 'Simkot', 'district' => '61'],
            ['municipalities' => 'Namkha', 'district' => '61'],
            ['municipalities' => 'Sarkegad', 'district' => '61'],
            ['municipalities' => 'Adanchuli', 'district' => '61'],
            ['municipalities' => 'Tanjakot', 'district' => '61'],

            ['municipalities' => 'Barkot', 'district' => '62'],
            ['municipalities' => 'Kuse', 'district' => '62'],
            ['municipalities' => 'Junichande', 'district' => '62'],
            ['municipalities' => 'Chhedagad', 'district' => '62'],
            ['municipalities' => 'Shivalaya', 'district' => '62'],
            ['municipalities' => 'Bheri malika', 'district' => '62'],
            ['municipalities' => 'Tribeni Nalagad', 'district' => '62'],

            ['municipalities' => 'Patarasi', 'district' => '63'],
            ['municipalities' => 'Kanaka sundari', 'district' => '63'],
            ['municipalities' => 'Sinja', 'district' => '63'],
            ['municipalities' => 'Chandannath', 'district' => '63'],
            ['municipalities' => 'Guthichaur', 'district' => '63'],
            ['municipalities' => 'Tatopani', 'district' => '63'],
            ['municipalities' => 'Tila', 'district' => '63'],
            ['municipalities' => 'Hima', 'district' => '63'],

            ['municipalities' => 'Palata', 'district' => '64'],
            ['municipalities' => 'Pachal Jharana', 'district' => '64'],
            ['municipalities' => 'Raskot', 'district' => '64'],
            ['municipalities' => 'Sanni Tribeni', 'district' => '64'],
            ['municipalities' => 'Naraharinath', 'district' => '64'],
            ['municipalities' => 'Khandachakra', 'district' => '64'],
            ['municipalities' => 'Tilagupha', 'district' => '64'],
            ['municipalities' => 'Mahawai', 'district' => '64'],
            ['municipalities' => 'Kalika', 'district' => '64'],

            ['municipalities' => 'Mugumakarmarog', 'district' => '65'],
            ['municipalities' => 'Chhayanath Rara', 'district' => '65'],
            ['municipalities' => 'Soru', 'district' => '65'],
            ['municipalities' => 'Khatyad', 'district' => '65'],

            ['municipalities' => 'Aathabisakot', 'district' => '66'],
            ['municipalities' => 'Sanibheri', 'district' => '66'],
            ['municipalities' => 'Banphikot', 'district' => '66'],
            ['municipalities' => 'Musikot', 'district' => '66'],
            ['municipalities' => 'Tribeni', 'district' => '66'],
            ['municipalities' => 'Chaurjhahari', 'district' => '66'],

            ['municipalities' => 'Darma', 'district' => '67'],
            ['municipalities' => 'Kumakha Malika', 'district' => '67'],
            ['municipalities' => 'Banagad kupind', 'district' => '67'],
            ['municipalities' => 'Dhorchaur', 'district' => '67'],
            ['municipalities' => 'Bagachour', 'district' => '67'],
            ['municipalities' => 'Chhatreshwori', 'district' => '67'],
            ['municipalities' => 'Sharada', 'district' => '67'],
            ['municipalities' => 'Kalimati', 'district' => '67'],
            ['municipalities' => 'Tribeni', 'district' => '67'],
            ['municipalities' => 'Kapurkot', 'district' => '67'],


            ['municipalities' => 'Chingad', 'district' => '68'],
            ['municipalities' => 'Simta', 'district' => '68'],
            ['municipalities' => 'Lekabeshi', 'district' => '68'],
            ['municipalities' => 'Gurbhakot', 'district' => '68'],
            ['municipalities' => 'Bheriganga', 'district' => '68'],
            ['municipalities' => 'Barahatal', 'district' => '68'],
            ['municipalities' => 'Panchapuri', 'district' => '68'],
            ['municipalities' => 'Chaukune', 'district' => '68'],


            ['municipalities' => 'Panchdebal Binayak', 'district' => '69'],
            ['municipalities' => 'Ramaroshan', 'district' => '69'],
            ['municipalities' => 'Mallekn', 'district' => '69'],
            ['municipalities' => 'Sanphebagar', 'district' => '69'],
            ['municipalities' => 'Chaurpati', 'district' => '69'],
            ['municipalities' => 'Mangalsen', 'district' => '69'],
            ['municipalities' => 'Bannigadhi  Jayagadh', 'district' => '69'],
            ['municipalities' => 'Kamal  Bazar', 'district' => '69'],
            ['municipalities' => 'Dhakari', 'district' => '69'],
            ['municipalities' => 'Turmakhand', 'district' => '69'],

            ['municipalities' => 'Dilasaini', 'district' => '70'],
            ['municipalities' => 'Dogada Kedar', 'district' => '70'],
            ['municipalities' => 'Puchaundi', 'district' => '70'],
            ['municipalities' => 'Surnaya', 'district' => '70'],
            ['municipalities' => 'Dasharatchand', 'district' => '70'],
            ['municipalities' => 'Pancheshwor', 'district' => '70'],
            ['municipalities' => 'Shivnath', 'district' => '70'],
            ['municipalities' => 'Melauli', 'district' => '70'],
            ['municipalities' => 'Patam', 'district' => '70'],
            ['municipalities' => 'Sigas', 'district' => '70'],

            ['municipalities' => 'Kanda', 'district' => '71'],
            ['municipalities' => 'Bungal', 'district' => '71'],
            ['municipalities' => 'Surma', 'district' => '71'],
            ['municipalities' => 'Talkot', 'district' => '71'],
            ['municipalities' => 'Masta', 'district' => '71'],
            ['municipalities' => 'Jayaprithbi', 'district' => '71'],
            ['municipalities' => 'Chhabis Pathibhara', 'district' => '71'],
            ['municipalities' => 'Durgathali', 'district' => '71'],
            ['municipalities' => 'Kedarsyun', 'district' => '71'],
            ['municipalities' => 'Bitthadchir', 'district' => '71'],
            ['municipalities' => 'Thalara', 'district' => '71'],
            ['municipalities' => 'Khaptad Chhanna', 'district' => '71'],

            ['municipalities' => 'Himali', 'district' => '72'],
            ['municipalities' => 'Gaumul', 'district' => '72'],
            ['municipalities' => 'Budhinanda', 'district' => '72'],
            ['municipalities' => 'Swami Kartik', 'district' => '72'],
            ['municipalities' => 'Pandab Gufa', 'district' => '72'],
            ['municipalities' => 'Badimalika', 'district' => '72'],
            ['municipalities' => 'Chhededaha', 'district' => '72'],
            ['municipalities' => 'Budhiganga', 'district' => '72'],
            ['municipalities' => 'Tribeni', 'district' => '72'],

            ['municipalities' => 'Nawadurga', 'district' => '73'],
            ['municipalities' => 'Amargadhi', 'district' => '73'],
            ['municipalities' => 'Ajayameru', 'district' => '73'],
            ['municipalities' => 'Bhageshwor', 'district' => '73'],
            ['municipalities' => 'Parashuram', 'district' => '73'],
            ['municipalities' => 'Aalital', 'district' => '73'],
            ['municipalities' => 'Ganyapdhura', 'district' => '73'],

            ['municipalities' => 'Byas', 'district' => '74'],
            ['municipalities' => 'Duhun', 'district' => '74'],
            ['municipalities' => 'Mahakali', 'district' => '74'],
            ['municipalities' => 'Naugad', 'district' => '74'],
            ['municipalities' => 'Apihimal', 'district' => '74'],
            ['municipalities' => 'Marma', 'district' => '74'],
            ['municipalities' => 'Shailyashikhar', 'district' => '74'],
            ['municipalities' => 'Malikarjun', 'district' => '74'],
            ['municipalities' => 'Lekam', 'district' => '74'],

            ['municipalities' => 'Purbichouki', 'district' => '75'],
            ['municipalities' => 'Sayal', 'district' => '75'],
            ['municipalities' => 'Shikhar', 'district' => '75'],
            ['municipalities' => 'Aadarsha', 'district' => '75'],
            ['municipalities' => 'Dipayal Silgadhi', 'district' => '75'],
            ['municipalities' => 'K.I. Singh', 'district' => '75'],
            ['municipalities' => 'Bogatan', 'district' => '75'],
            ['municipalities' => 'Badi Kedar', 'district' => '75'],
            ['municipalities' => 'Jorayal', 'district' => '75'],

            ['municipalities' => 'Mahanyal', 'district' => '76'],
            ['municipalities' => 'Chure', 'district' => '76'],
            ['municipalities' => 'Godawari', 'district' => '76'],
            ['municipalities' => 'Gauriganga', 'district' => '76'],
            ['municipalities' => 'Ghogadghodi', 'district' => '76'],
            ['municipalities' => 'Bardagoriya', 'district' => '76'],
            ['municipalities' => 'Laxmi Chuha', 'district' => '76'],
            ['municipalities' => 'Janki', 'district' => '76'],
            ['municipalities' => 'Joshipur', 'district' => '76'],
            ['municipalities' => 'Tikapur', 'district' => '76'],
            ['municipalities' => 'Bhajani', 'district' => '76'],
            ['municipalities' => 'Kailari', 'district' => '76'],
            ['municipalities' => 'Dhangadhi', 'district' => '76'],

            ['municipalities' => 'Krishnapur', 'district' => '77'],
            ['municipalities' => 'Shuklaphanta', 'district' => '77'],
            ['municipalities' => 'Bedkot', 'district' => '77'],
            ['municipalities' => 'Bhimdatta', 'district' => '77'],
            ['municipalities' => 'Mahakali', 'district' => '77'],
            ['municipalities' => 'Laljhadi', 'district' => '77'],
            ['municipalities' => 'Punarbas', 'district' => '77'],
            ['municipalities' => 'Belouri', 'district' => '77'],
            ['municipalities' => 'Beldani', 'district' => '77'],
        ];

        Municipality::insert($data);
    }
}
